In [1]:
from PIL import Image
from numpy import array
import numpy as np
import math
import os 
import subprocess 
from osgeo import gdal 
import matplotlib.pyplot as plt

In [2]:
for i in range(3):
    W1 = float(input("Slop Weight :"))
    W2 = float(input("aspect Weight:"))
    if (W1+W2)!=1:
        print("jame adad vrad shed bayad 1 bashad")
        continue
    else:
        break

Slop Weight :0.6
aspect Weight:0.5
jame adad vrad shed bayad 1 bashad
Slop Weight :0.6
aspect Weight:0.4


In [32]:
fn1 = r'F:\H\UT\Term\2\Advanced programming GIS\FFFFFF\samani\data4\dem\dem.tif'
dem = gdal.Open(fn1)
slp1 = gdal.DEMProcessing("dem.tif",dem,"slope", computeEdges = True)
slp1Array = slp1.GetRasterBand(1).ReadAsArray()
print("Slop:",slp1Array)

aspect1 = gdal.DEMProcessing("aspect.tif",dem,"aspect" , computeEdges = True )
aspect1Array = aspect1.GetRasterBand(1).ReadAsArray()
print("aspect direction:",aspect1Array)
# plt.figure()
# plt.imshow(slp1Array)
# plt.colorbar()
# plt.show()

Slop: [[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
aspect direction: [[ 33.08706   65.87883   64.690315 ... 160.07376  148.91711  158.6991  ]
 [ 50.65269   68.01487   66.334015 ... 162.43979  155.4205   148.87283 ]
 [ 70.11954   80.0271    77.37349  ... 158.6854   160.98975  159.43372 ]
 ...
 [259.38635  255.68018  241.97272  ... 156.26443  139.3265   128.24715 ]
 [229.65755  226.46043  211.55112  ... 157.37918  139.38069  124.971344]
 [198.60605  211.5278   202.98126  ... 169.7926   160.80685  164.84326 ]]


In [35]:
fn2 = r'F:\H\UT\Term\2\Advanced programming GIS\FFFFFF\samani\data4\dem\dem.tif'
dem2 = gdal.Open(fn2)
slp2 = gdal.DEMProcessing("dem.tif",dem2,"slope", computeEdges = True)
slp2Array = slp2.GetRasterBand(1).ReadAsArray()
print(slp2Array)


aspect2 = gdal.DEMProcessing("aspect.tif",dem,"aspect", computeEdges = True)
aspect2Array = aspect2.GetRasterBand(1).ReadAsArray()
print("slope direction:",aspect2Array)

# plt.figure()
# plt.imshow(slp2Array)
# plt.colorbar()
# plt.show()

[[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
slope direction: [[ 33.08706   65.87883   64.690315 ... 160.07376  148.91711  158.6991  ]
 [ 50.65269   68.01487   66.334015 ... 162.43979  155.4205   148.87283 ]
 [ 70.11954   80.0271    77.37349  ... 158.6854   160.98975  159.43372 ]
 ...
 [259.38635  255.68018  241.97272  ... 156.26443  139.3265   128.24715 ]
 [229.65755  226.46043  211.55112  ... 157.37918  139.38069  124.971344]
 [198.60605  211.5278   202.98126  ... 169.7926   160.80685  164.84326 ]]


In [5]:
fn3 = r'F:\H\UT\Term\2\Advanced programming GIS\FFFFFF\samani\data4\dem\dem.tif'
dem3 = gdal.Open(fn3)
slp3 = gdal.DEMProcessing("dem.tif",dem,"slope", computeEdges = True)
slp3Array = slp3.GetRasterBand(1).ReadAsArray()
print(slp3Array)

aspect3 = gdal.DEMProcessing("aspect.tif",dem,"aspect", computeEdges = True)
aspect3Array = aspect3.GetRasterBand(1).ReadAsArray()
print("slope direction:",aspect3Array)

# plt.figure()
# plt.imshow(slp3Array)
# plt.colorbar()
# plt.show()

[[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
slope direction: [[ 33.08706   65.87883   64.690315 ... 160.07376  148.91711  158.6991  ]
 [ 50.65269   68.01487   66.334015 ... 162.43979  155.4205   148.87283 ]
 [ 70.11954   80.0271    77.37349  ... 158.6854   160.98975  159.43372 ]
 ...
 [259.38635  255.68018  241.97272  ... 156.26443  139.3265   128.24715 ]
 [229.65755  226.46043  211.55112  ... 157.37918  139.38069  124.971344]
 [198.60605  211.5278   202.98126  ... 169.7926   160.80685  164.84326 ]]


In [6]:
# arr_max=slp3Array.max()
# arr_min=slp3Array.min()
# print(slp3Array.shape)
# print(diff_arr)
# print(arr_max)
# print(arr_min)

In [7]:
def normalize(arr, t_min, t_max):
    arr_max=arr.max()
    arr_min=arr.min()
    norm_arr = []
    diff = t_max - t_min
    diff_arr = arr_max - arr_min
    for i in range(2925):
        for j in range(2793):
                temp = (((arr[i][j] - arr_min) * diff) / diff_arr)
                norm_arr.append(temp)
    return norm_arr

In [8]:
# # # gives range staring from 1 and ending at 1

range_to_normalize = (0, 1)
normalized_slp_array_1 = normalize(slp1Array,range_to_normalize[0],range_to_normalize[1])
normalized_aspect_array_1 = normalize(aspect1Array,range_to_normalize[0],range_to_normalize[1])

normalized_slp_array_w1 = [item *W1 for item in normalized_slp_array_1]
normalized_aspect_array_w1 = [item *W2 for item in normalized_aspect_array_1]

# # # display original and normalized array
print("Original Array = ", slp1Array)
print("Normal Slop Array * W = ",normalized_slp_array_w1[0:10])
print("Normal aspect Array * W = ",normalized_aspect_array_w1[0:10])

Original Array =  [[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
Normal Slop Array * W =  [0.10307761057718932, 0.25296154902103496, 0.23596507408007975, 0.0870177992323382, 0.05761657162968743, 0.046736825532554385, 0.05473955976235423, 0.07655805144387293, 0.06956818593197708, 0.0628855949705254]
Normal aspect Array * W =  [0.03676350175607961, 0.07319890472105711, 0.07187832912740591, 0.03157805057743234, 0.02286229065412662, 0.010059656098145485, 0.35050892866301187, 0.32879120297832054, 0.33955634268521706, 0.3685263876487556]


In [9]:
# # # gives range staring from 1 and ending at 1
range_to_normalize = (0, 1)
normalized_slp_array_2 = normalize(slp2Array,range_to_normalize[0],range_to_normalize[1])
normalized_aspect_array_2 = normalize(aspect2Array,range_to_normalize[0],range_to_normalize[1])

normalized_slp_array_w2 = [item *W1 for item in normalized_slp_array_2]
normalized_aspect_array_w2 = [item *W2 for item in normalized_aspect_array_2]

# # # display original and normalized array
print("Original Array = ", slp2Array)
print("Normal Slop Array * W = ",normalized_slp_array_w2[0:10])
print("Normal aspect Array * W = ",normalized_aspect_array_w2[0:10])

Original Array =  [[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
Normal Slop Array * W =  [0.10307761057718932, 0.25296154902103496, 0.23596507408007975, 0.0870177992323382, 0.05761657162968743, 0.046736825532554385, 0.05473955976235423, 0.07655805144387293, 0.06956818593197708, 0.0628855949705254]
Normal aspect Array * W =  [0.03676350175607961, 0.07319890472105711, 0.07187832912740591, 0.03157805057743234, 0.02286229065412662, 0.010059656098145485, 0.35050892866301187, 0.32879120297832054, 0.33955634268521706, 0.3685263876487556]


In [10]:
# # # gives range staring from 1 and ending at 1
range_to_normalize = (0, 1)
normalized_slp_array_3 = normalize(slp2Array,range_to_normalize[0],range_to_normalize[1])
normalized_aspect_array_3 = normalize(aspect2Array,range_to_normalize[0],range_to_normalize[1])

normalized_slp_array_w3 = [item *W1 for item in normalized_slp_array_3]
normalized_aspect_array_w3 = [item *W2 for item in normalized_aspect_array_3]

# # # display original and normalized array
print("Original Array = ", slp3Array)
print("Normal Slop Array * W = ",normalized_slp_array_w3[0:10])
print("Normal aspect Array * W = ",normalized_aspect_array_w3[0:10])

Original Array =  [[14.464219  35.491188  33.10678   ... 41.815197  41.98034   36.332943 ]
 [10.506695  31.165728  34.886547  ... 41.831104  40.699036  37.49361  ]
 [ 5.2992964 24.988955  32.73089   ... 39.73455   39.9938    36.795834 ]
 ...
 [ 7.7422976 10.2472     9.836968  ...  5.817905   6.7466326  8.010784 ]
 [ 9.084121  10.841125  11.689538  ...  5.5191584  6.2433925  7.1146493]
 [ 9.593957  11.562633  11.640335  ... 10.271223   9.971402   8.838001 ]]
Normal Slop Array * W =  [0.10307761057718932, 0.25296154902103496, 0.23596507408007975, 0.0870177992323382, 0.05761657162968743, 0.046736825532554385, 0.05473955976235423, 0.07655805144387293, 0.06956818593197708, 0.0628855949705254]
Normal aspect Array * W =  [0.03676350175607961, 0.07319890472105711, 0.07187832912740591, 0.03157805057743234, 0.02286229065412662, 0.010059656098145485, 0.35050892866301187, 0.32879120297832054, 0.33955634268521706, 0.3685263876487556]


In [13]:
slp_array_Final = [x + y + z for x, y, z in zip(normalized_slp_array_w3, normalized_slp_array_w2,normalized_slp_array_w3)]
aspect_array_Final = [x + y + z for x, y, z in zip(normalized_aspect_array_w1, normalized_aspect_array_w2,normalized_aspect_array_w3)]
print(slp_array_Final[0:10])
print(aspect_array_Final[0:10])

[0.30923283173156796, 0.7588846470631049, 0.7078952222402393, 0.2610533976970146, 0.1728497148890623, 0.14021047659766317, 0.16421867928706269, 0.22967415433161878, 0.20870455779593125, 0.1886567849115762]
[0.11029050526823883, 0.21959671416317134, 0.21563498738221773, 0.09473415173229702, 0.06858687196237986, 0.030178968294436455, 1.0515267859890356, 0.9863736089349616, 1.0186690280556512, 1.1055791629462668]
